console.log("Manipulating website using JS Window object");
let a = window;
// window.alert("Hello Dhara");
// alert("Hello Dhara");
// a = prompt("Why be a king when you can be a God. Type your name");
// a = confirm("confirm!!");
// a=innerHeight;
// a=innerWidth;
// a=scrollX;
// a=location;
// a=location.toString();
a=history;
console.log(a); 
console.clear();